packet {
  process_tree {
    processes {
      pid: 1
      ppid: 0
      cmdline: "init"
    }
    processes {
      pid: 2
      ppid: 1
      cmdline: "two_thread_process"
    }
    processes {
      pid: 4
      ppid: 1
      cmdline: "single_thread_process"
    }
    threads {
      tid: 3
      tgid: 2
    }
  }
}

packet {
  ftrace_events {
    cpu: 0
    event {
      timestamp: 1
      pid: 1
      sched_switch {
        prev_comm: "init"
        prev_pid: 1
        next_comm: "two_thread_process"
        next_pid: 3
      }
    }
    event {
      timestamp: 50
      pid: 3
      cpu_frequency {
        state: 50
        cpu_id: 0
      }
    }
    event {
      timestamp: 100
      pid: 3
      sched_switch {
        prev_comm: "two_thread_process"
        prev_pid: 3
        next_comm: "two_thread_process"
        next_pid: 2
      }
    }
    event {
      timestamp: 115
      pid: 2
      sched_switch {
        prev_comm: "two_thread_process"
        prev_pid: 2
        next_comm: "two_thread_process"
        next_pid: 3
      }
    }
  }
}

packet {
  ftrace_events {
    cpu: 1
    event {
      timestamp: 50
      pid: 4
      sched_switch {
        prev_comm: "single_thread_process"
        prev_pid: 4
        next_comm: "init"
        next_pid: 1
      }
    }
    event {
      timestamp: 120
      pid: 1
      sched_switch {
        prev_comm: "init"
        prev_pid: 1
        next_comm: "two_thread_process"
        next_pid: 2
      }
    }
    event {
      timestamp: 170
      pid: 2
      sched_switch {
        prev_comm: "two_thread_process"
        prev_pid: 2
        next_comm: "init"
        next_pid: 0
      }
    }
    event {
      timestamp: 250
      pid: 0
      sched_switch {
        prev_comm: "init"
        prev_pid: 0
        next_comm: "two_thread_process"
        next_pid: 2
      }
    }
    event {
      timestamp: 390
      pid: 2
      sched_switch {
        prev_comm: "two_thread_process"
        prev_pid: 2
        next_comm: "single_thread_process"
        next_pid: 4
      }
    }
    event {
      timestamp: 400
      pid: 4
      cpu_frequency {
        state: 100
        cpu_id: 0
      }
    }
  }
}
