# Copyright (C) 2018 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This file is automatically generated by tools/gen_build. Do not edit.

# GN target: //tools/skippy:skippy
cc_binary(
    name = "tools_skippy_skippy",
    srcs = [
        "include/perfetto/base/build_config.h",
        "include/perfetto/base/file_utils.h",
        "include/perfetto/base/logging.h",
        "include/perfetto/base/metatrace.h",
        "include/perfetto/base/page_allocator.h",
        "include/perfetto/base/scoped_file.h",
        "include/perfetto/base/small_set.h",
        "include/perfetto/base/string_splitter.h",
        "include/perfetto/base/string_utils.h",
        "include/perfetto/base/task_runner.h",
        "include/perfetto/base/temp_file.h",
        "include/perfetto/base/thread_checker.h",
        "include/perfetto/base/time.h",
        "include/perfetto/base/unix_task_runner.h",
        "include/perfetto/base/utils.h",
        "include/perfetto/base/watchdog.h",
        "include/perfetto/base/watchdog_noop.h",
        "include/perfetto/base/watchdog_posix.h",
        "include/perfetto/base/weak_ptr.h",
        "src/base/file_utils.cc",
        "src/base/metatrace.cc",
        "src/base/page_allocator.cc",
        "src/base/string_splitter.cc",
        "src/base/string_utils.cc",
        "src/base/temp_file.cc",
        "src/base/thread_checker.cc",
        "src/base/time.cc",
        "src/base/unix_task_runner.cc",
        "src/base/virtual_destructors.cc",
        "src/base/watchdog_posix.cc",
        "tools/skippy/skippy.cc",
    ],
    copts = [
        "-Iinclude",
    ],
    linkopts = [
        "-lpthread",
        "-lrt",
    ],
)
