// Autogenerated by:
// ../../tools/ftrace_proto_gen/ftrace_descriptor_gen.h
// Do not edit.

#ifndef SRC_TRACE_PROCESSOR_FTRACE_DESCRIPTORS_H_
#define SRC_TRACE_PROCESSOR_FTRACE_DESCRIPTORS_H_

#include <array>
#include "perfetto/protozero/proto_utils.h"

namespace perfetto {

using protozero::proto_utils::ProtoFieldType;

struct FieldDescriptor {
  const char* name;
  ProtoFieldType type;
};

struct MessageDescriptor {
  const char* name;
  FieldDescriptor fields[32];
};

static std::array<MessageDescriptor, 328> descriptors{{
    {},
    {},
    {},
    {
        "print",
        {
            {},
            {"ip", ProtoFieldType::kProtoUint64},
            {"buf", ProtoFieldType::kProtoString},
        },
    },
    {
        "sched_switch",
        {
            {},
            {"prev_comm", ProtoFieldType::kProtoString},
            {"prev_pid", ProtoFieldType::kProtoInt32},
            {"prev_prio", ProtoFieldType::kProtoInt32},
            {"prev_state", ProtoFieldType::kProtoInt64},
            {"next_comm", ProtoFieldType::kProtoString},
            {"next_pid", ProtoFieldType::kProtoInt32},
            {"next_prio", ProtoFieldType::kProtoInt32},
        },
    },
    {},
    {},
    {},
    {},
    {},
    {},
    {
        "cpu_frequency",
        {
            {},
            {"state", ProtoFieldType::kProtoUint32},
            {"cpu_id", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "cpu_frequency_limits",
        {
            {},
            {"min_freq", ProtoFieldType::kProtoUint32},
            {"max_freq", ProtoFieldType::kProtoUint32},
            {"cpu_id", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "cpu_idle",
        {
            {},
            {"state", ProtoFieldType::kProtoUint32},
            {"cpu_id", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "clock_enable",
        {
            {},
            {"name", ProtoFieldType::kProtoString},
            {"state", ProtoFieldType::kProtoUint64},
            {"cpu_id", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "clock_disable",
        {
            {},
            {"name", ProtoFieldType::kProtoString},
            {"state", ProtoFieldType::kProtoUint64},
            {"cpu_id", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "clock_set_rate",
        {
            {},
            {"name", ProtoFieldType::kProtoString},
            {"state", ProtoFieldType::kProtoUint64},
            {"cpu_id", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "sched_wakeup",
        {
            {},
            {"comm", ProtoFieldType::kProtoString},
            {"pid", ProtoFieldType::kProtoInt32},
            {"prio", ProtoFieldType::kProtoInt32},
            {"success", ProtoFieldType::kProtoInt32},
            {"target_cpu", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "sched_blocked_reason",
        {
            {},
            {"pid", ProtoFieldType::kProtoInt32},
            {"caller", ProtoFieldType::kProtoUint64},
            {"io_wait", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "sched_cpu_hotplug",
        {
            {},
            {"affected_cpu", ProtoFieldType::kProtoInt32},
            {"error", ProtoFieldType::kProtoInt32},
            {"status", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "sched_waking",
        {
            {},
            {"comm", ProtoFieldType::kProtoString},
            {"pid", ProtoFieldType::kProtoInt32},
            {"prio", ProtoFieldType::kProtoInt32},
            {"success", ProtoFieldType::kProtoInt32},
            {"target_cpu", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ipi_entry",
        {
            {},
            {"reason", ProtoFieldType::kProtoString},
        },
    },
    {
        "ipi_exit",
        {
            {},
            {"reason", ProtoFieldType::kProtoString},
        },
    },
    {
        "ipi_raise",
        {
            {},
            {"target_cpus", ProtoFieldType::kProtoUint32},
            {"reason", ProtoFieldType::kProtoString},
        },
    },
    {
        "softirq_entry",
        {
            {},
            {"vec", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "softirq_exit",
        {
            {},
            {"vec", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "softirq_raise",
        {
            {},
            {"vec", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "i2c_read",
        {
            {},
            {"adapter_nr", ProtoFieldType::kProtoInt32},
            {"msg_nr", ProtoFieldType::kProtoUint32},
            {"addr", ProtoFieldType::kProtoUint32},
            {"flags", ProtoFieldType::kProtoUint32},
            {"len", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "i2c_write",
        {
            {},
            {"adapter_nr", ProtoFieldType::kProtoInt32},
            {"msg_nr", ProtoFieldType::kProtoUint32},
            {"addr", ProtoFieldType::kProtoUint32},
            {"flags", ProtoFieldType::kProtoUint32},
            {"len", ProtoFieldType::kProtoUint32},
            {"buf", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "i2c_result",
        {
            {},
            {"adapter_nr", ProtoFieldType::kProtoInt32},
            {"nr_msgs", ProtoFieldType::kProtoUint32},
            {"ret", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "i2c_reply",
        {
            {},
            {"adapter_nr", ProtoFieldType::kProtoInt32},
            {"msg_nr", ProtoFieldType::kProtoUint32},
            {"addr", ProtoFieldType::kProtoUint32},
            {"flags", ProtoFieldType::kProtoUint32},
            {"len", ProtoFieldType::kProtoUint32},
            {"buf", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "smbus_read",
        {
            {},
            {"adapter_nr", ProtoFieldType::kProtoInt32},
            {"flags", ProtoFieldType::kProtoUint32},
            {"addr", ProtoFieldType::kProtoUint32},
            {"command", ProtoFieldType::kProtoUint32},
            {"protocol", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "smbus_write",
        {
            {},
            {"adapter_nr", ProtoFieldType::kProtoInt32},
            {"addr", ProtoFieldType::kProtoUint32},
            {"flags", ProtoFieldType::kProtoUint32},
            {"command", ProtoFieldType::kProtoUint32},
            {"len", ProtoFieldType::kProtoUint32},
            {"protocol", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "smbus_result",
        {
            {},
            {"adapter_nr", ProtoFieldType::kProtoInt32},
            {"addr", ProtoFieldType::kProtoUint32},
            {"flags", ProtoFieldType::kProtoUint32},
            {"read_write", ProtoFieldType::kProtoUint32},
            {"command", ProtoFieldType::kProtoUint32},
            {"res", ProtoFieldType::kProtoInt32},
            {"protocol", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "smbus_reply",
        {
            {},
            {"adapter_nr", ProtoFieldType::kProtoInt32},
            {"addr", ProtoFieldType::kProtoUint32},
            {"flags", ProtoFieldType::kProtoUint32},
            {"command", ProtoFieldType::kProtoUint32},
            {"len", ProtoFieldType::kProtoUint32},
            {"protocol", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "lowmemory_kill",
        {
            {},
            {"comm", ProtoFieldType::kProtoString},
            {"pid", ProtoFieldType::kProtoInt32},
            {"pagecache_size", ProtoFieldType::kProtoInt64},
            {"pagecache_limit", ProtoFieldType::kProtoInt64},
            {"free", ProtoFieldType::kProtoInt64},
        },
    },
    {
        "irq_handler_entry",
        {
            {},
            {"irq", ProtoFieldType::kProtoInt32},
            {"name", ProtoFieldType::kProtoString},
            {"handler", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "irq_handler_exit",
        {
            {},
            {"irq", ProtoFieldType::kProtoInt32},
            {"ret", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "sync_pt",
        {
            {},
            {"timeline", ProtoFieldType::kProtoString},
            {"value", ProtoFieldType::kProtoString},
        },
    },
    {
        "sync_timeline",
        {
            {},
            {"name", ProtoFieldType::kProtoString},
            {"value", ProtoFieldType::kProtoString},
        },
    },
    {
        "sync_wait",
        {
            {},
            {"name", ProtoFieldType::kProtoString},
            {"status", ProtoFieldType::kProtoInt32},
            {"begin", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_da_write_begin",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"pos", ProtoFieldType::kProtoInt64},
            {"len", ProtoFieldType::kProtoUint32},
            {"flags", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_da_write_end",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"pos", ProtoFieldType::kProtoInt64},
            {"len", ProtoFieldType::kProtoUint32},
            {"copied", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_sync_file_enter",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"parent", ProtoFieldType::kProtoUint64},
            {"datasync", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ext4_sync_file_exit",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"ret", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "block_rq_issue",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"sector", ProtoFieldType::kProtoUint64},
            {"nr_sector", ProtoFieldType::kProtoUint32},
            {"bytes", ProtoFieldType::kProtoUint32},
            {"rwbs", ProtoFieldType::kProtoString},
            {"comm", ProtoFieldType::kProtoString},
            {"cmd", ProtoFieldType::kProtoString},
        },
    },
    {
        "mm_vmscan_direct_reclaim_begin",
        {
            {},
            {"order", ProtoFieldType::kProtoInt32},
            {"may_writepage", ProtoFieldType::kProtoInt32},
            {"gfp_flags", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "mm_vmscan_direct_reclaim_end",
        {
            {},
            {"nr_reclaimed", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "mm_vmscan_kswapd_wake",
        {
            {},
            {"nid", ProtoFieldType::kProtoInt32},
            {"order", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "mm_vmscan_kswapd_sleep",
        {
            {},
            {"nid", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "binder_transaction",
        {
            {},
            {"debug_id", ProtoFieldType::kProtoInt32},
            {"target_node", ProtoFieldType::kProtoInt32},
            {"to_proc", ProtoFieldType::kProtoInt32},
            {"to_thread", ProtoFieldType::kProtoInt32},
            {"reply", ProtoFieldType::kProtoInt32},
            {"code", ProtoFieldType::kProtoUint32},
            {"flags", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "binder_transaction_received",
        {
            {},
            {"debug_id", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "binder_set_priority",
        {
            {},
            {"proc", ProtoFieldType::kProtoInt32},
            {"thread", ProtoFieldType::kProtoInt32},
            {"old_prio", ProtoFieldType::kProtoUint32},
            {"new_prio", ProtoFieldType::kProtoUint32},
            {"desired_prio", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "binder_lock",
        {
            {},
            {"tag", ProtoFieldType::kProtoString},
        },
    },
    {
        "binder_locked",
        {
            {},
            {"tag", ProtoFieldType::kProtoString},
        },
    },
    {
        "binder_unlock",
        {
            {},
            {"tag", ProtoFieldType::kProtoString},
        },
    },
    {
        "workqueue_activate_work",
        {
            {},
            {"work", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "workqueue_execute_end",
        {
            {},
            {"work", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "workqueue_execute_start",
        {
            {},
            {"work", ProtoFieldType::kProtoUint64},
            {"function", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "workqueue_queue_work",
        {
            {},
            {"work", ProtoFieldType::kProtoUint64},
            {"function", ProtoFieldType::kProtoUint64},
            {"workqueue", ProtoFieldType::kProtoUint64},
            {"req_cpu", ProtoFieldType::kProtoUint32},
            {"cpu", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "regulator_disable",
        {
            {},
            {"name", ProtoFieldType::kProtoString},
        },
    },
    {
        "regulator_disable_complete",
        {
            {},
            {"name", ProtoFieldType::kProtoString},
        },
    },
    {
        "regulator_enable",
        {
            {},
            {"name", ProtoFieldType::kProtoString},
        },
    },
    {
        "regulator_enable_complete",
        {
            {},
            {"name", ProtoFieldType::kProtoString},
        },
    },
    {
        "regulator_enable_delay",
        {
            {},
            {"name", ProtoFieldType::kProtoString},
        },
    },
    {
        "regulator_set_voltage",
        {
            {},
            {"name", ProtoFieldType::kProtoString},
            {"min", ProtoFieldType::kProtoInt32},
            {"max", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "regulator_set_voltage_complete",
        {
            {},
            {"name", ProtoFieldType::kProtoString},
            {"val", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "cgroup_attach_task",
        {
            {},
            {"dst_root", ProtoFieldType::kProtoInt32},
            {"dst_id", ProtoFieldType::kProtoInt32},
            {"pid", ProtoFieldType::kProtoInt32},
            {"comm", ProtoFieldType::kProtoString},
            {"cname", ProtoFieldType::kProtoString},
        },
    },
    {
        "cgroup_mkdir",
        {
            {},
            {"root", ProtoFieldType::kProtoInt32},
            {"id", ProtoFieldType::kProtoInt32},
            {"cname", ProtoFieldType::kProtoString},
        },
    },
    {
        "cgroup_remount",
        {
            {},
            {"root", ProtoFieldType::kProtoInt32},
            {"ss_mask", ProtoFieldType::kProtoUint32},
            {"name", ProtoFieldType::kProtoString},
        },
    },
    {
        "cgroup_rmdir",
        {
            {},
            {"root", ProtoFieldType::kProtoInt32},
            {"id", ProtoFieldType::kProtoInt32},
            {"cname", ProtoFieldType::kProtoString},
        },
    },
    {
        "cgroup_transfer_tasks",
        {
            {},
            {"dst_root", ProtoFieldType::kProtoInt32},
            {"dst_id", ProtoFieldType::kProtoInt32},
            {"pid", ProtoFieldType::kProtoInt32},
            {"comm", ProtoFieldType::kProtoString},
            {"cname", ProtoFieldType::kProtoString},
        },
    },
    {
        "cgroup_destroy_root",
        {
            {},
            {"root", ProtoFieldType::kProtoInt32},
            {"ss_mask", ProtoFieldType::kProtoUint32},
            {"name", ProtoFieldType::kProtoString},
        },
    },
    {
        "cgroup_release",
        {
            {},
            {"root", ProtoFieldType::kProtoInt32},
            {"id", ProtoFieldType::kProtoInt32},
            {"cname", ProtoFieldType::kProtoString},
        },
    },
    {
        "cgroup_rename",
        {
            {},
            {"root", ProtoFieldType::kProtoInt32},
            {"id", ProtoFieldType::kProtoInt32},
            {"cname", ProtoFieldType::kProtoString},
        },
    },
    {
        "cgroup_setup_root",
        {
            {},
            {"root", ProtoFieldType::kProtoInt32},
            {"ss_mask", ProtoFieldType::kProtoUint32},
            {"name", ProtoFieldType::kProtoString},
        },
    },
    {
        "mdp_cmd_kickoff",
        {
            {},
            {"ctl_num", ProtoFieldType::kProtoUint32},
            {"kickoff_cnt", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "mdp_commit",
        {
            {},
            {"num", ProtoFieldType::kProtoUint32},
            {"play_cnt", ProtoFieldType::kProtoUint32},
            {"clk_rate", ProtoFieldType::kProtoUint32},
            {"bandwidth", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "mdp_perf_set_ot",
        {
            {},
            {"pnum", ProtoFieldType::kProtoUint32},
            {"xin_id", ProtoFieldType::kProtoUint32},
            {"rd_lim", ProtoFieldType::kProtoUint32},
            {"is_vbif_rt", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "mdp_sspp_change",
        {
            {},
            {"num", ProtoFieldType::kProtoUint32},
            {"play_cnt", ProtoFieldType::kProtoUint32},
            {"mixer", ProtoFieldType::kProtoUint32},
            {"stage", ProtoFieldType::kProtoUint32},
            {"flags", ProtoFieldType::kProtoUint32},
            {"format", ProtoFieldType::kProtoUint32},
            {"img_w", ProtoFieldType::kProtoUint32},
            {"img_h", ProtoFieldType::kProtoUint32},
            {"src_x", ProtoFieldType::kProtoUint32},
            {"src_y", ProtoFieldType::kProtoUint32},
            {"src_w", ProtoFieldType::kProtoUint32},
            {"src_h", ProtoFieldType::kProtoUint32},
            {"dst_x", ProtoFieldType::kProtoUint32},
            {"dst_y", ProtoFieldType::kProtoUint32},
            {"dst_w", ProtoFieldType::kProtoUint32},
            {"dst_h", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "tracing_mark_write",
        {
            {},
            {"pid", ProtoFieldType::kProtoInt32},
            {"trace_name", ProtoFieldType::kProtoString},
            {"trace_begin", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "mdp_cmd_pingpong_done",
        {
            {},
            {"ctl_num", ProtoFieldType::kProtoUint32},
            {"intf_num", ProtoFieldType::kProtoUint32},
            {"pp_num", ProtoFieldType::kProtoUint32},
            {"koff_cnt", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "mdp_compare_bw",
        {
            {},
            {"new_ab", ProtoFieldType::kProtoUint64},
            {"new_ib", ProtoFieldType::kProtoUint64},
            {"new_wb", ProtoFieldType::kProtoUint64},
            {"old_ab", ProtoFieldType::kProtoUint64},
            {"old_ib", ProtoFieldType::kProtoUint64},
            {"old_wb", ProtoFieldType::kProtoUint64},
            {"params_changed", ProtoFieldType::kProtoUint32},
            {"update_bw", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "mdp_perf_set_panic_luts",
        {
            {},
            {"pnum", ProtoFieldType::kProtoUint32},
            {"fmt", ProtoFieldType::kProtoUint32},
            {"mode", ProtoFieldType::kProtoUint32},
            {"panic_lut", ProtoFieldType::kProtoUint32},
            {"robust_lut", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "mdp_sspp_set",
        {
            {},
            {"num", ProtoFieldType::kProtoUint32},
            {"play_cnt", ProtoFieldType::kProtoUint32},
            {"mixer", ProtoFieldType::kProtoUint32},
            {"stage", ProtoFieldType::kProtoUint32},
            {"flags", ProtoFieldType::kProtoUint32},
            {"format", ProtoFieldType::kProtoUint32},
            {"img_w", ProtoFieldType::kProtoUint32},
            {"img_h", ProtoFieldType::kProtoUint32},
            {"src_x", ProtoFieldType::kProtoUint32},
            {"src_y", ProtoFieldType::kProtoUint32},
            {"src_w", ProtoFieldType::kProtoUint32},
            {"src_h", ProtoFieldType::kProtoUint32},
            {"dst_x", ProtoFieldType::kProtoUint32},
            {"dst_y", ProtoFieldType::kProtoUint32},
            {"dst_w", ProtoFieldType::kProtoUint32},
            {"dst_h", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "mdp_cmd_readptr_done",
        {
            {},
            {"ctl_num", ProtoFieldType::kProtoUint32},
            {"koff_cnt", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "mdp_misr_crc",
        {
            {},
            {"block_id", ProtoFieldType::kProtoUint32},
            {"vsync_cnt", ProtoFieldType::kProtoUint32},
            {"crc", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "mdp_perf_set_qos_luts",
        {
            {},
            {"pnum", ProtoFieldType::kProtoUint32},
            {"fmt", ProtoFieldType::kProtoUint32},
            {"intf", ProtoFieldType::kProtoUint32},
            {"rot", ProtoFieldType::kProtoUint32},
            {"fl", ProtoFieldType::kProtoUint32},
            {"lut", ProtoFieldType::kProtoUint32},
            {"linear", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "mdp_trace_counter",
        {
            {},
            {"pid", ProtoFieldType::kProtoInt32},
            {"counter_name", ProtoFieldType::kProtoString},
            {"value", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "mdp_cmd_release_bw",
        {
            {},
            {"ctl_num", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "mdp_mixer_update",
        {
            {},
            {"mixer_num", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "mdp_perf_set_wm_levels",
        {
            {},
            {"pnum", ProtoFieldType::kProtoUint32},
            {"use_space", ProtoFieldType::kProtoUint32},
            {"priority_bytes", ProtoFieldType::kProtoUint32},
            {"wm0", ProtoFieldType::kProtoUint32},
            {"wm1", ProtoFieldType::kProtoUint32},
            {"wm2", ProtoFieldType::kProtoUint32},
            {"mb_cnt", ProtoFieldType::kProtoUint32},
            {"mb_size", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "mdp_video_underrun_done",
        {
            {},
            {"ctl_num", ProtoFieldType::kProtoUint32},
            {"underrun_cnt", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "mdp_cmd_wait_pingpong",
        {
            {},
            {"ctl_num", ProtoFieldType::kProtoUint32},
            {"kickoff_cnt", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "mdp_perf_prefill_calc",
        {
            {},
            {"pnum", ProtoFieldType::kProtoUint32},
            {"latency_buf", ProtoFieldType::kProtoUint32},
            {"ot", ProtoFieldType::kProtoUint32},
            {"y_buf", ProtoFieldType::kProtoUint32},
            {"y_scaler", ProtoFieldType::kProtoUint32},
            {"pp_lines", ProtoFieldType::kProtoUint32},
            {"pp_bytes", ProtoFieldType::kProtoUint32},
            {"post_sc", ProtoFieldType::kProtoUint32},
            {"fbc_bytes", ProtoFieldType::kProtoUint32},
            {"prefill_bytes", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "mdp_perf_update_bus",
        {
            {},
            {"client", ProtoFieldType::kProtoInt32},
            {"ab_quota", ProtoFieldType::kProtoUint64},
            {"ib_quota", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "rotator_bw_ao_as_context",
        {
            {},
            {"state", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "mm_filemap_add_to_page_cache",
        {
            {},
            {"pfn", ProtoFieldType::kProtoUint64},
            {"i_ino", ProtoFieldType::kProtoUint64},
            {"index", ProtoFieldType::kProtoUint64},
            {"s_dev", ProtoFieldType::kProtoUint64},
            {"page", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "mm_filemap_delete_from_page_cache",
        {
            {},
            {"pfn", ProtoFieldType::kProtoUint64},
            {"i_ino", ProtoFieldType::kProtoUint64},
            {"index", ProtoFieldType::kProtoUint64},
            {"s_dev", ProtoFieldType::kProtoUint64},
            {"page", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "mm_compaction_begin",
        {
            {},
            {"zone_start", ProtoFieldType::kProtoUint64},
            {"migrate_pfn", ProtoFieldType::kProtoUint64},
            {"free_pfn", ProtoFieldType::kProtoUint64},
            {"zone_end", ProtoFieldType::kProtoUint64},
            {"sync", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "mm_compaction_defer_compaction",
        {
            {},
            {"nid", ProtoFieldType::kProtoInt32},
            {"idx", ProtoFieldType::kProtoUint32},
            {"order", ProtoFieldType::kProtoInt32},
            {"considered", ProtoFieldType::kProtoUint32},
            {"defer_shift", ProtoFieldType::kProtoUint32},
            {"order_failed", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "mm_compaction_deferred",
        {
            {},
            {"nid", ProtoFieldType::kProtoInt32},
            {"idx", ProtoFieldType::kProtoUint32},
            {"order", ProtoFieldType::kProtoInt32},
            {"considered", ProtoFieldType::kProtoUint32},
            {"defer_shift", ProtoFieldType::kProtoUint32},
            {"order_failed", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "mm_compaction_defer_reset",
        {
            {},
            {"nid", ProtoFieldType::kProtoInt32},
            {"idx", ProtoFieldType::kProtoUint32},
            {"order", ProtoFieldType::kProtoInt32},
            {"considered", ProtoFieldType::kProtoUint32},
            {"defer_shift", ProtoFieldType::kProtoUint32},
            {"order_failed", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "mm_compaction_end",
        {
            {},
            {"zone_start", ProtoFieldType::kProtoUint64},
            {"migrate_pfn", ProtoFieldType::kProtoUint64},
            {"free_pfn", ProtoFieldType::kProtoUint64},
            {"zone_end", ProtoFieldType::kProtoUint64},
            {"sync", ProtoFieldType::kProtoUint32},
            {"status", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "mm_compaction_finished",
        {
            {},
            {"nid", ProtoFieldType::kProtoInt32},
            {"idx", ProtoFieldType::kProtoUint32},
            {"order", ProtoFieldType::kProtoInt32},
            {"ret", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "mm_compaction_isolate_freepages",
        {
            {},
            {"start_pfn", ProtoFieldType::kProtoUint64},
            {"end_pfn", ProtoFieldType::kProtoUint64},
            {"nr_scanned", ProtoFieldType::kProtoUint64},
            {"nr_taken", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "mm_compaction_isolate_migratepages",
        {
            {},
            {"start_pfn", ProtoFieldType::kProtoUint64},
            {"end_pfn", ProtoFieldType::kProtoUint64},
            {"nr_scanned", ProtoFieldType::kProtoUint64},
            {"nr_taken", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "mm_compaction_kcompactd_sleep",
        {
            {},
            {"nid", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "mm_compaction_kcompactd_wake",
        {
            {},
            {"nid", ProtoFieldType::kProtoInt32},
            {"order", ProtoFieldType::kProtoInt32},
            {"classzone_idx", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "mm_compaction_migratepages",
        {
            {},
            {"nr_migrated", ProtoFieldType::kProtoUint64},
            {"nr_failed", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "mm_compaction_suitable",
        {
            {},
            {"nid", ProtoFieldType::kProtoInt32},
            {"idx", ProtoFieldType::kProtoUint32},
            {"order", ProtoFieldType::kProtoInt32},
            {"ret", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "mm_compaction_try_to_compact_pages",
        {
            {},
            {"order", ProtoFieldType::kProtoInt32},
            {"gfp_mask", ProtoFieldType::kProtoUint32},
            {"mode", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "mm_compaction_wakeup_kcompactd",
        {
            {},
            {"nid", ProtoFieldType::kProtoInt32},
            {"order", ProtoFieldType::kProtoInt32},
            {"classzone_idx", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "suspend_resume",
        {
            {},
            {"action", ProtoFieldType::kProtoString},
            {"val", ProtoFieldType::kProtoInt32},
            {"start", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "sched_wakeup_new",
        {
            {},
            {"comm", ProtoFieldType::kProtoString},
            {"pid", ProtoFieldType::kProtoInt32},
            {"prio", ProtoFieldType::kProtoInt32},
            {"success", ProtoFieldType::kProtoInt32},
            {"target_cpu", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "block_bio_backmerge",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"sector", ProtoFieldType::kProtoUint64},
            {"nr_sector", ProtoFieldType::kProtoUint32},
            {"rwbs", ProtoFieldType::kProtoString},
            {"comm", ProtoFieldType::kProtoString},
        },
    },
    {
        "block_bio_bounce",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"sector", ProtoFieldType::kProtoUint64},
            {"nr_sector", ProtoFieldType::kProtoUint32},
            {"rwbs", ProtoFieldType::kProtoString},
            {"comm", ProtoFieldType::kProtoString},
        },
    },
    {
        "block_bio_complete",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"sector", ProtoFieldType::kProtoUint64},
            {"nr_sector", ProtoFieldType::kProtoUint32},
            {"error", ProtoFieldType::kProtoInt32},
            {"rwbs", ProtoFieldType::kProtoString},
        },
    },
    {
        "block_bio_frontmerge",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"sector", ProtoFieldType::kProtoUint64},
            {"nr_sector", ProtoFieldType::kProtoUint32},
            {"rwbs", ProtoFieldType::kProtoString},
            {"comm", ProtoFieldType::kProtoString},
        },
    },
    {
        "block_bio_queue",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"sector", ProtoFieldType::kProtoUint64},
            {"nr_sector", ProtoFieldType::kProtoUint32},
            {"rwbs", ProtoFieldType::kProtoString},
            {"comm", ProtoFieldType::kProtoString},
        },
    },
    {
        "block_bio_remap",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"sector", ProtoFieldType::kProtoUint64},
            {"nr_sector", ProtoFieldType::kProtoUint32},
            {"old_dev", ProtoFieldType::kProtoUint64},
            {"old_sector", ProtoFieldType::kProtoUint64},
            {"rwbs", ProtoFieldType::kProtoString},
        },
    },
    {
        "block_dirty_buffer",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"sector", ProtoFieldType::kProtoUint64},
            {"size", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "block_getrq",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"sector", ProtoFieldType::kProtoUint64},
            {"nr_sector", ProtoFieldType::kProtoUint32},
            {"rwbs", ProtoFieldType::kProtoString},
            {"comm", ProtoFieldType::kProtoString},
        },
    },
    {
        "block_plug",
        {
            {},
            {"comm", ProtoFieldType::kProtoString},
        },
    },
    {
        "block_rq_abort",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"sector", ProtoFieldType::kProtoUint64},
            {"nr_sector", ProtoFieldType::kProtoUint32},
            {"errors", ProtoFieldType::kProtoInt32},
            {"rwbs", ProtoFieldType::kProtoString},
            {"cmd", ProtoFieldType::kProtoString},
        },
    },
    {
        "block_rq_complete",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"sector", ProtoFieldType::kProtoUint64},
            {"nr_sector", ProtoFieldType::kProtoUint32},
            {"errors", ProtoFieldType::kProtoInt32},
            {"rwbs", ProtoFieldType::kProtoString},
            {"cmd", ProtoFieldType::kProtoString},
        },
    },
    {
        "block_rq_insert",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"sector", ProtoFieldType::kProtoUint64},
            {"nr_sector", ProtoFieldType::kProtoUint32},
            {"bytes", ProtoFieldType::kProtoUint32},
            {"rwbs", ProtoFieldType::kProtoString},
            {"comm", ProtoFieldType::kProtoString},
            {"cmd", ProtoFieldType::kProtoString},
        },
    },
    {},
    {
        "block_rq_remap",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"sector", ProtoFieldType::kProtoUint64},
            {"nr_sector", ProtoFieldType::kProtoUint32},
            {"old_dev", ProtoFieldType::kProtoUint64},
            {"old_sector", ProtoFieldType::kProtoUint64},
            {"nr_bios", ProtoFieldType::kProtoUint32},
            {"rwbs", ProtoFieldType::kProtoString},
        },
    },
    {
        "block_rq_requeue",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"sector", ProtoFieldType::kProtoUint64},
            {"nr_sector", ProtoFieldType::kProtoUint32},
            {"errors", ProtoFieldType::kProtoInt32},
            {"rwbs", ProtoFieldType::kProtoString},
            {"cmd", ProtoFieldType::kProtoString},
        },
    },
    {
        "block_sleeprq",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"sector", ProtoFieldType::kProtoUint64},
            {"nr_sector", ProtoFieldType::kProtoUint32},
            {"rwbs", ProtoFieldType::kProtoString},
            {"comm", ProtoFieldType::kProtoString},
        },
    },
    {
        "block_split",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"sector", ProtoFieldType::kProtoUint64},
            {"new_sector", ProtoFieldType::kProtoUint64},
            {"rwbs", ProtoFieldType::kProtoString},
            {"comm", ProtoFieldType::kProtoString},
        },
    },
    {
        "block_touch_buffer",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"sector", ProtoFieldType::kProtoUint64},
            {"size", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "block_unplug",
        {
            {},
            {"nr_rq", ProtoFieldType::kProtoInt32},
            {"comm", ProtoFieldType::kProtoString},
        },
    },
    {
        "ext4_alloc_da_blocks",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"data_blocks", ProtoFieldType::kProtoUint32},
            {"meta_blocks", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_allocate_blocks",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"block", ProtoFieldType::kProtoUint64},
            {"len", ProtoFieldType::kProtoUint32},
            {"logical", ProtoFieldType::kProtoUint32},
            {"lleft", ProtoFieldType::kProtoUint32},
            {"lright", ProtoFieldType::kProtoUint32},
            {"goal", ProtoFieldType::kProtoUint64},
            {"pleft", ProtoFieldType::kProtoUint64},
            {"pright", ProtoFieldType::kProtoUint64},
            {"flags", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_allocate_inode",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"dir", ProtoFieldType::kProtoUint64},
            {"mode", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_begin_ordered_truncate",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"new_size", ProtoFieldType::kProtoInt64},
        },
    },
    {
        "ext4_collapse_range",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"offset", ProtoFieldType::kProtoInt64},
            {"len", ProtoFieldType::kProtoInt64},
        },
    },
    {
        "ext4_da_release_space",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"i_blocks", ProtoFieldType::kProtoUint64},
            {"freed_blocks", ProtoFieldType::kProtoInt32},
            {"reserved_data_blocks", ProtoFieldType::kProtoInt32},
            {"reserved_meta_blocks", ProtoFieldType::kProtoInt32},
            {"allocated_meta_blocks", ProtoFieldType::kProtoInt32},
            {"mode", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_da_reserve_space",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"i_blocks", ProtoFieldType::kProtoUint64},
            {"reserved_data_blocks", ProtoFieldType::kProtoInt32},
            {"reserved_meta_blocks", ProtoFieldType::kProtoInt32},
            {"mode", ProtoFieldType::kProtoUint32},
            {"md_needed", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ext4_da_update_reserve_space",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"i_blocks", ProtoFieldType::kProtoUint64},
            {"used_blocks", ProtoFieldType::kProtoInt32},
            {"reserved_data_blocks", ProtoFieldType::kProtoInt32},
            {"reserved_meta_blocks", ProtoFieldType::kProtoInt32},
            {"allocated_meta_blocks", ProtoFieldType::kProtoInt32},
            {"quota_claim", ProtoFieldType::kProtoInt32},
            {"mode", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_da_write_pages",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"first_page", ProtoFieldType::kProtoUint64},
            {"nr_to_write", ProtoFieldType::kProtoInt64},
            {"sync_mode", ProtoFieldType::kProtoInt32},
            {"b_blocknr", ProtoFieldType::kProtoUint64},
            {"b_size", ProtoFieldType::kProtoUint32},
            {"b_state", ProtoFieldType::kProtoUint32},
            {"io_done", ProtoFieldType::kProtoInt32},
            {"pages_written", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ext4_da_write_pages_extent",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"lblk", ProtoFieldType::kProtoUint64},
            {"len", ProtoFieldType::kProtoUint32},
            {"flags", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_direct_IO_enter",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"pos", ProtoFieldType::kProtoInt64},
            {"len", ProtoFieldType::kProtoUint64},
            {"rw", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ext4_direct_IO_exit",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"pos", ProtoFieldType::kProtoInt64},
            {"len", ProtoFieldType::kProtoUint64},
            {"rw", ProtoFieldType::kProtoInt32},
            {"ret", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ext4_discard_blocks",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"blk", ProtoFieldType::kProtoUint64},
            {"count", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "ext4_discard_preallocations",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "ext4_drop_inode",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"drop", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ext4_es_cache_extent",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"lblk", ProtoFieldType::kProtoUint32},
            {"len", ProtoFieldType::kProtoUint32},
            {"pblk", ProtoFieldType::kProtoUint64},
            {"status", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_es_find_delayed_extent_range_enter",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"lblk", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_es_find_delayed_extent_range_exit",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"lblk", ProtoFieldType::kProtoUint32},
            {"len", ProtoFieldType::kProtoUint32},
            {"pblk", ProtoFieldType::kProtoUint64},
            {"status", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "ext4_es_insert_extent",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"lblk", ProtoFieldType::kProtoUint32},
            {"len", ProtoFieldType::kProtoUint32},
            {"pblk", ProtoFieldType::kProtoUint64},
            {"status", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "ext4_es_lookup_extent_enter",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"lblk", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_es_lookup_extent_exit",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"lblk", ProtoFieldType::kProtoUint32},
            {"len", ProtoFieldType::kProtoUint32},
            {"pblk", ProtoFieldType::kProtoUint64},
            {"status", ProtoFieldType::kProtoUint64},
            {"found", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ext4_es_remove_extent",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"lblk", ProtoFieldType::kProtoInt64},
            {"len", ProtoFieldType::kProtoInt64},
        },
    },
    {
        "ext4_es_shrink",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"nr_shrunk", ProtoFieldType::kProtoInt32},
            {"scan_time", ProtoFieldType::kProtoUint64},
            {"nr_skipped", ProtoFieldType::kProtoInt32},
            {"retried", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ext4_es_shrink_count",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"nr_to_scan", ProtoFieldType::kProtoInt32},
            {"cache_cnt", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ext4_es_shrink_scan_enter",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"nr_to_scan", ProtoFieldType::kProtoInt32},
            {"cache_cnt", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ext4_es_shrink_scan_exit",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"nr_shrunk", ProtoFieldType::kProtoInt32},
            {"cache_cnt", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ext4_evict_inode",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"nlink", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ext4_ext_convert_to_initialized_enter",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"m_lblk", ProtoFieldType::kProtoUint32},
            {"m_len", ProtoFieldType::kProtoUint32},
            {"u_lblk", ProtoFieldType::kProtoUint32},
            {"u_len", ProtoFieldType::kProtoUint32},
            {"u_pblk", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "ext4_ext_convert_to_initialized_fastpath",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"m_lblk", ProtoFieldType::kProtoUint32},
            {"m_len", ProtoFieldType::kProtoUint32},
            {"u_lblk", ProtoFieldType::kProtoUint32},
            {"u_len", ProtoFieldType::kProtoUint32},
            {"u_pblk", ProtoFieldType::kProtoUint64},
            {"i_lblk", ProtoFieldType::kProtoUint32},
            {"i_len", ProtoFieldType::kProtoUint32},
            {"i_pblk", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "ext4_ext_handle_unwritten_extents",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"flags", ProtoFieldType::kProtoInt32},
            {"lblk", ProtoFieldType::kProtoUint32},
            {"pblk", ProtoFieldType::kProtoUint64},
            {"len", ProtoFieldType::kProtoUint32},
            {"allocated", ProtoFieldType::kProtoUint32},
            {"newblk", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "ext4_ext_in_cache",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"lblk", ProtoFieldType::kProtoUint32},
            {"ret", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ext4_ext_load_extent",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"pblk", ProtoFieldType::kProtoUint64},
            {"lblk", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_ext_map_blocks_enter",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"lblk", ProtoFieldType::kProtoUint32},
            {"len", ProtoFieldType::kProtoUint32},
            {"flags", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_ext_map_blocks_exit",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"flags", ProtoFieldType::kProtoUint32},
            {"pblk", ProtoFieldType::kProtoUint64},
            {"lblk", ProtoFieldType::kProtoUint32},
            {"len", ProtoFieldType::kProtoUint32},
            {"mflags", ProtoFieldType::kProtoUint32},
            {"ret", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ext4_ext_put_in_cache",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"lblk", ProtoFieldType::kProtoUint32},
            {"len", ProtoFieldType::kProtoUint32},
            {"start", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "ext4_ext_remove_space",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"start", ProtoFieldType::kProtoUint32},
            {"end", ProtoFieldType::kProtoUint32},
            {"depth", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ext4_ext_remove_space_done",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"start", ProtoFieldType::kProtoUint32},
            {"end", ProtoFieldType::kProtoUint32},
            {"depth", ProtoFieldType::kProtoInt32},
            {"partial", ProtoFieldType::kProtoInt64},
            {"eh_entries", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_ext_rm_idx",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"pblk", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "ext4_ext_rm_leaf",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"partial", ProtoFieldType::kProtoInt64},
            {"start", ProtoFieldType::kProtoUint32},
            {"ee_lblk", ProtoFieldType::kProtoUint32},
            {"ee_pblk", ProtoFieldType::kProtoUint64},
            {"ee_len", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ext4_ext_show_extent",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"pblk", ProtoFieldType::kProtoUint64},
            {"lblk", ProtoFieldType::kProtoUint32},
            {"len", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_fallocate_enter",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"offset", ProtoFieldType::kProtoInt64},
            {"len", ProtoFieldType::kProtoInt64},
            {"mode", ProtoFieldType::kProtoInt32},
            {"pos", ProtoFieldType::kProtoInt64},
        },
    },
    {
        "ext4_fallocate_exit",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"pos", ProtoFieldType::kProtoInt64},
            {"blocks", ProtoFieldType::kProtoUint32},
            {"ret", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ext4_find_delalloc_range",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"from", ProtoFieldType::kProtoUint32},
            {"to", ProtoFieldType::kProtoUint32},
            {"reverse", ProtoFieldType::kProtoInt32},
            {"found", ProtoFieldType::kProtoInt32},
            {"found_blk", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_forget",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"block", ProtoFieldType::kProtoUint64},
            {"is_metadata", ProtoFieldType::kProtoInt32},
            {"mode", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_free_blocks",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"block", ProtoFieldType::kProtoUint64},
            {"count", ProtoFieldType::kProtoUint64},
            {"flags", ProtoFieldType::kProtoInt32},
            {"mode", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_free_inode",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"uid", ProtoFieldType::kProtoUint32},
            {"gid", ProtoFieldType::kProtoUint32},
            {"blocks", ProtoFieldType::kProtoUint64},
            {"mode", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_get_implied_cluster_alloc_exit",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"flags", ProtoFieldType::kProtoUint32},
            {"lblk", ProtoFieldType::kProtoUint32},
            {"pblk", ProtoFieldType::kProtoUint64},
            {"len", ProtoFieldType::kProtoUint32},
            {"ret", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ext4_get_reserved_cluster_alloc",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"lblk", ProtoFieldType::kProtoUint32},
            {"len", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_ind_map_blocks_enter",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"lblk", ProtoFieldType::kProtoUint32},
            {"len", ProtoFieldType::kProtoUint32},
            {"flags", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_ind_map_blocks_exit",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"flags", ProtoFieldType::kProtoUint32},
            {"pblk", ProtoFieldType::kProtoUint64},
            {"lblk", ProtoFieldType::kProtoUint32},
            {"len", ProtoFieldType::kProtoUint32},
            {"mflags", ProtoFieldType::kProtoUint32},
            {"ret", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ext4_insert_range",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"offset", ProtoFieldType::kProtoInt64},
            {"len", ProtoFieldType::kProtoInt64},
        },
    },
    {
        "ext4_invalidatepage",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"index", ProtoFieldType::kProtoUint64},
            {"offset", ProtoFieldType::kProtoUint64},
            {"length", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_journal_start",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ip", ProtoFieldType::kProtoUint64},
            {"blocks", ProtoFieldType::kProtoInt32},
            {"rsv_blocks", ProtoFieldType::kProtoInt32},
            {"nblocks", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ext4_journal_start_reserved",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ip", ProtoFieldType::kProtoUint64},
            {"blocks", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ext4_journalled_invalidatepage",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"index", ProtoFieldType::kProtoUint64},
            {"offset", ProtoFieldType::kProtoUint64},
            {"length", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_journalled_write_end",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"pos", ProtoFieldType::kProtoInt64},
            {"len", ProtoFieldType::kProtoUint32},
            {"copied", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_load_inode",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "ext4_load_inode_bitmap",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"group", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_mark_inode_dirty",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"ip", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "ext4_mb_bitmap_load",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"group", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_mb_buddy_bitmap_load",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"group", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_mb_discard_preallocations",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"needed", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ext4_mb_new_group_pa",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"pa_pstart", ProtoFieldType::kProtoUint64},
            {"pa_lstart", ProtoFieldType::kProtoUint64},
            {"pa_len", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_mb_new_inode_pa",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"pa_pstart", ProtoFieldType::kProtoUint64},
            {"pa_lstart", ProtoFieldType::kProtoUint64},
            {"pa_len", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_mb_release_group_pa",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"pa_pstart", ProtoFieldType::kProtoUint64},
            {"pa_len", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_mb_release_inode_pa",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"block", ProtoFieldType::kProtoUint64},
            {"count", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_mballoc_alloc",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"orig_logical", ProtoFieldType::kProtoUint32},
            {"orig_start", ProtoFieldType::kProtoInt32},
            {"orig_group", ProtoFieldType::kProtoUint32},
            {"orig_len", ProtoFieldType::kProtoInt32},
            {"goal_logical", ProtoFieldType::kProtoUint32},
            {"goal_start", ProtoFieldType::kProtoInt32},
            {"goal_group", ProtoFieldType::kProtoUint32},
            {"goal_len", ProtoFieldType::kProtoInt32},
            {"result_logical", ProtoFieldType::kProtoUint32},
            {"result_start", ProtoFieldType::kProtoInt32},
            {"result_group", ProtoFieldType::kProtoUint32},
            {"result_len", ProtoFieldType::kProtoInt32},
            {"found", ProtoFieldType::kProtoUint32},
            {"groups", ProtoFieldType::kProtoUint32},
            {"buddy", ProtoFieldType::kProtoUint32},
            {"flags", ProtoFieldType::kProtoUint32},
            {"tail", ProtoFieldType::kProtoUint32},
            {"cr", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_mballoc_discard",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"result_start", ProtoFieldType::kProtoInt32},
            {"result_group", ProtoFieldType::kProtoUint32},
            {"result_len", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ext4_mballoc_free",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"result_start", ProtoFieldType::kProtoInt32},
            {"result_group", ProtoFieldType::kProtoUint32},
            {"result_len", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ext4_mballoc_prealloc",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"orig_logical", ProtoFieldType::kProtoUint32},
            {"orig_start", ProtoFieldType::kProtoInt32},
            {"orig_group", ProtoFieldType::kProtoUint32},
            {"orig_len", ProtoFieldType::kProtoInt32},
            {"result_logical", ProtoFieldType::kProtoUint32},
            {"result_start", ProtoFieldType::kProtoInt32},
            {"result_group", ProtoFieldType::kProtoUint32},
            {"result_len", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ext4_other_inode_update_time",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"orig_ino", ProtoFieldType::kProtoUint64},
            {"uid", ProtoFieldType::kProtoUint32},
            {"gid", ProtoFieldType::kProtoUint32},
            {"mode", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_punch_hole",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"offset", ProtoFieldType::kProtoInt64},
            {"len", ProtoFieldType::kProtoInt64},
            {"mode", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ext4_read_block_bitmap_load",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"group", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_readpage",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"index", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "ext4_releasepage",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"index", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "ext4_remove_blocks",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"from", ProtoFieldType::kProtoUint32},
            {"to", ProtoFieldType::kProtoUint32},
            {"partial", ProtoFieldType::kProtoInt64},
            {"ee_pblk", ProtoFieldType::kProtoUint64},
            {"ee_lblk", ProtoFieldType::kProtoUint32},
            {"ee_len", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_request_blocks",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"len", ProtoFieldType::kProtoUint32},
            {"logical", ProtoFieldType::kProtoUint32},
            {"lleft", ProtoFieldType::kProtoUint32},
            {"lright", ProtoFieldType::kProtoUint32},
            {"goal", ProtoFieldType::kProtoUint64},
            {"pleft", ProtoFieldType::kProtoUint64},
            {"pright", ProtoFieldType::kProtoUint64},
            {"flags", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_request_inode",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"dir", ProtoFieldType::kProtoUint64},
            {"mode", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_sync_fs",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"wait", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ext4_trim_all_free",
        {
            {},
            {"dev_major", ProtoFieldType::kProtoInt32},
            {"dev_minor", ProtoFieldType::kProtoInt32},
            {"group", ProtoFieldType::kProtoUint32},
            {"start", ProtoFieldType::kProtoInt32},
            {"len", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ext4_trim_extent",
        {
            {},
            {"dev_major", ProtoFieldType::kProtoInt32},
            {"dev_minor", ProtoFieldType::kProtoInt32},
            {"group", ProtoFieldType::kProtoUint32},
            {"start", ProtoFieldType::kProtoInt32},
            {"len", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ext4_truncate_enter",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"blocks", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "ext4_truncate_exit",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"blocks", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "ext4_unlink_enter",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"parent", ProtoFieldType::kProtoUint64},
            {"size", ProtoFieldType::kProtoInt64},
        },
    },
    {
        "ext4_unlink_exit",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"ret", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ext4_write_begin",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"pos", ProtoFieldType::kProtoInt64},
            {"len", ProtoFieldType::kProtoUint32},
            {"flags", ProtoFieldType::kProtoUint32},
        },
    },
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {},
    {
        "ext4_write_end",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"pos", ProtoFieldType::kProtoInt64},
            {"len", ProtoFieldType::kProtoUint32},
            {"copied", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_writepage",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"index", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "ext4_writepages",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"nr_to_write", ProtoFieldType::kProtoInt64},
            {"pages_skipped", ProtoFieldType::kProtoInt64},
            {"range_start", ProtoFieldType::kProtoInt64},
            {"range_end", ProtoFieldType::kProtoInt64},
            {"writeback_index", ProtoFieldType::kProtoUint64},
            {"sync_mode", ProtoFieldType::kProtoInt32},
            {"for_kupdate", ProtoFieldType::kProtoUint32},
            {"range_cyclic", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ext4_writepages_result",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"ret", ProtoFieldType::kProtoInt32},
            {"pages_written", ProtoFieldType::kProtoInt32},
            {"pages_skipped", ProtoFieldType::kProtoInt64},
            {"writeback_index", ProtoFieldType::kProtoUint64},
            {"sync_mode", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ext4_zero_range",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"offset", ProtoFieldType::kProtoInt64},
            {"len", ProtoFieldType::kProtoInt64},
            {"mode", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "task_newtask",
        {
            {},
            {"pid", ProtoFieldType::kProtoInt32},
            {"comm", ProtoFieldType::kProtoString},
            {"clone_flags", ProtoFieldType::kProtoUint64},
            {"oom_score_adj", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "task_rename",
        {
            {},
            {"pid", ProtoFieldType::kProtoInt32},
            {"oldcomm", ProtoFieldType::kProtoString},
            {"newcomm", ProtoFieldType::kProtoString},
            {"oom_score_adj", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "sched_process_exec",
        {
            {},
            {"filename", ProtoFieldType::kProtoString},
            {"pid", ProtoFieldType::kProtoInt32},
            {"old_pid", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "sched_process_exit",
        {
            {},
            {"comm", ProtoFieldType::kProtoString},
            {"pid", ProtoFieldType::kProtoInt32},
            {"tgid", ProtoFieldType::kProtoInt32},
            {"prio", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "sched_process_fork",
        {
            {},
            {"parent_comm", ProtoFieldType::kProtoString},
            {"parent_pid", ProtoFieldType::kProtoInt32},
            {"child_comm", ProtoFieldType::kProtoString},
            {"child_pid", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "sched_process_free",
        {
            {},
            {"comm", ProtoFieldType::kProtoString},
            {"pid", ProtoFieldType::kProtoInt32},
            {"prio", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "sched_process_hang",
        {
            {},
            {"comm", ProtoFieldType::kProtoString},
            {"pid", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "sched_process_wait",
        {
            {},
            {"comm", ProtoFieldType::kProtoString},
            {"pid", ProtoFieldType::kProtoInt32},
            {"prio", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "f2fs_do_submit_bio",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"btype", ProtoFieldType::kProtoInt32},
            {"sync", ProtoFieldType::kProtoUint32},
            {"sector", ProtoFieldType::kProtoUint64},
            {"size", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "f2fs_evict_inode",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"pino", ProtoFieldType::kProtoUint64},
            {"mode", ProtoFieldType::kProtoUint32},
            {"size", ProtoFieldType::kProtoInt64},
            {"nlink", ProtoFieldType::kProtoUint32},
            {"blocks", ProtoFieldType::kProtoUint64},
            {"advise", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "f2fs_fallocate",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"mode", ProtoFieldType::kProtoInt32},
            {"offset", ProtoFieldType::kProtoInt64},
            {"len", ProtoFieldType::kProtoInt64},
            {"size", ProtoFieldType::kProtoInt64},
            {"blocks", ProtoFieldType::kProtoUint64},
            {"ret", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "f2fs_get_data_block",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"iblock", ProtoFieldType::kProtoUint64},
            {"bh_start", ProtoFieldType::kProtoUint64},
            {"bh_size", ProtoFieldType::kProtoUint64},
            {"ret", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "f2fs_get_victim",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"type", ProtoFieldType::kProtoInt32},
            {"gc_type", ProtoFieldType::kProtoInt32},
            {"alloc_mode", ProtoFieldType::kProtoInt32},
            {"gc_mode", ProtoFieldType::kProtoInt32},
            {"victim", ProtoFieldType::kProtoUint32},
            {"ofs_unit", ProtoFieldType::kProtoUint32},
            {"pre_victim", ProtoFieldType::kProtoUint32},
            {"prefree", ProtoFieldType::kProtoUint32},
            {"free", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "f2fs_iget",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"pino", ProtoFieldType::kProtoUint64},
            {"mode", ProtoFieldType::kProtoUint32},
            {"size", ProtoFieldType::kProtoInt64},
            {"nlink", ProtoFieldType::kProtoUint32},
            {"blocks", ProtoFieldType::kProtoUint64},
            {"advise", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "f2fs_iget_exit",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"ret", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "f2fs_new_inode",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"ret", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "f2fs_readpage",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"index", ProtoFieldType::kProtoUint64},
            {"blkaddr", ProtoFieldType::kProtoUint64},
            {"type", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "f2fs_reserve_new_block",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"nid", ProtoFieldType::kProtoUint32},
            {"ofs_in_node", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "f2fs_set_page_dirty",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"type", ProtoFieldType::kProtoInt32},
            {"dir", ProtoFieldType::kProtoInt32},
            {"index", ProtoFieldType::kProtoUint64},
            {"dirty", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "f2fs_submit_write_page",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"type", ProtoFieldType::kProtoInt32},
            {"index", ProtoFieldType::kProtoUint64},
            {"block", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "f2fs_sync_file_enter",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"pino", ProtoFieldType::kProtoUint64},
            {"mode", ProtoFieldType::kProtoUint32},
            {"size", ProtoFieldType::kProtoInt64},
            {"nlink", ProtoFieldType::kProtoUint32},
            {"blocks", ProtoFieldType::kProtoUint64},
            {"advise", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "f2fs_sync_file_exit",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"need_cp", ProtoFieldType::kProtoUint32},
            {"datasync", ProtoFieldType::kProtoInt32},
            {"ret", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "f2fs_sync_fs",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"dirty", ProtoFieldType::kProtoInt32},
            {"wait", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "f2fs_truncate",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"pino", ProtoFieldType::kProtoUint64},
            {"mode", ProtoFieldType::kProtoUint32},
            {"size", ProtoFieldType::kProtoInt64},
            {"nlink", ProtoFieldType::kProtoUint32},
            {"blocks", ProtoFieldType::kProtoUint64},
            {"advise", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "f2fs_truncate_blocks_enter",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"size", ProtoFieldType::kProtoInt64},
            {"blocks", ProtoFieldType::kProtoUint64},
            {"from", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "f2fs_truncate_blocks_exit",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"ret", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "f2fs_truncate_data_blocks_range",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"nid", ProtoFieldType::kProtoUint32},
            {"ofs", ProtoFieldType::kProtoUint32},
            {"free", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "f2fs_truncate_inode_blocks_enter",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"size", ProtoFieldType::kProtoInt64},
            {"blocks", ProtoFieldType::kProtoUint64},
            {"from", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "f2fs_truncate_inode_blocks_exit",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"ret", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "f2fs_truncate_node",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"nid", ProtoFieldType::kProtoUint32},
            {"blk_addr", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "f2fs_truncate_nodes_enter",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"nid", ProtoFieldType::kProtoUint32},
            {"blk_addr", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "f2fs_truncate_nodes_exit",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"ret", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "f2fs_truncate_partial_nodes",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"nid", ProtoFieldType::kProtoUint32},
            {"depth", ProtoFieldType::kProtoInt32},
            {"err", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "f2fs_unlink_enter",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"size", ProtoFieldType::kProtoInt64},
            {"blocks", ProtoFieldType::kProtoUint64},
            {"name", ProtoFieldType::kProtoString},
        },
    },
    {
        "f2fs_unlink_exit",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"ret", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "f2fs_vm_page_mkwrite",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"type", ProtoFieldType::kProtoInt32},
            {"dir", ProtoFieldType::kProtoInt32},
            {"index", ProtoFieldType::kProtoUint64},
            {"dirty", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "f2fs_write_begin",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"pos", ProtoFieldType::kProtoInt64},
            {"len", ProtoFieldType::kProtoUint32},
            {"flags", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "f2fs_write_checkpoint",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"is_umount", ProtoFieldType::kProtoUint32},
            {"msg", ProtoFieldType::kProtoString},
        },
    },
    {
        "f2fs_write_end",
        {
            {},
            {"dev", ProtoFieldType::kProtoUint64},
            {"ino", ProtoFieldType::kProtoUint64},
            {"pos", ProtoFieldType::kProtoInt64},
            {"len", ProtoFieldType::kProtoUint32},
            {"copied", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "alloc_pages_iommu_end",
        {
            {},
            {"gfp_flags", ProtoFieldType::kProtoUint32},
            {"order", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "alloc_pages_iommu_fail",
        {
            {},
            {"gfp_flags", ProtoFieldType::kProtoUint32},
            {"order", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "alloc_pages_iommu_start",
        {
            {},
            {"gfp_flags", ProtoFieldType::kProtoUint32},
            {"order", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "alloc_pages_sys_end",
        {
            {},
            {"gfp_flags", ProtoFieldType::kProtoUint32},
            {"order", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "alloc_pages_sys_fail",
        {
            {},
            {"gfp_flags", ProtoFieldType::kProtoUint32},
            {"order", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "alloc_pages_sys_start",
        {
            {},
            {"gfp_flags", ProtoFieldType::kProtoUint32},
            {"order", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "dma_alloc_contiguous_retry",
        {
            {},
            {"tries", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "iommu_map_range",
        {
            {},
            {"chunk_size", ProtoFieldType::kProtoUint64},
            {"len", ProtoFieldType::kProtoUint64},
            {"pa", ProtoFieldType::kProtoUint64},
            {"va", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "iommu_sec_ptbl_map_range_end",
        {
            {},
            {"len", ProtoFieldType::kProtoUint64},
            {"num", ProtoFieldType::kProtoInt32},
            {"pa", ProtoFieldType::kProtoUint32},
            {"sec_id", ProtoFieldType::kProtoInt32},
            {"va", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "iommu_sec_ptbl_map_range_start",
        {
            {},
            {"len", ProtoFieldType::kProtoUint64},
            {"num", ProtoFieldType::kProtoInt32},
            {"pa", ProtoFieldType::kProtoUint32},
            {"sec_id", ProtoFieldType::kProtoInt32},
            {"va", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "ion_alloc_buffer_end",
        {
            {},
            {"client_name", ProtoFieldType::kProtoString},
            {"flags", ProtoFieldType::kProtoUint32},
            {"heap_name", ProtoFieldType::kProtoString},
            {"len", ProtoFieldType::kProtoUint64},
            {"mask", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ion_alloc_buffer_fail",
        {
            {},
            {"client_name", ProtoFieldType::kProtoString},
            {"error", ProtoFieldType::kProtoInt64},
            {"flags", ProtoFieldType::kProtoUint32},
            {"heap_name", ProtoFieldType::kProtoString},
            {"len", ProtoFieldType::kProtoUint64},
            {"mask", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ion_alloc_buffer_fallback",
        {
            {},
            {"client_name", ProtoFieldType::kProtoString},
            {"error", ProtoFieldType::kProtoInt64},
            {"flags", ProtoFieldType::kProtoUint32},
            {"heap_name", ProtoFieldType::kProtoString},
            {"len", ProtoFieldType::kProtoUint64},
            {"mask", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ion_alloc_buffer_start",
        {
            {},
            {"client_name", ProtoFieldType::kProtoString},
            {"flags", ProtoFieldType::kProtoUint32},
            {"heap_name", ProtoFieldType::kProtoString},
            {"len", ProtoFieldType::kProtoUint64},
            {"mask", ProtoFieldType::kProtoUint32},
        },
    },
    {
        "ion_cp_alloc_retry",
        {
            {},
            {"tries", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ion_cp_secure_buffer_end",
        {
            {},
            {"align", ProtoFieldType::kProtoUint64},
            {"flags", ProtoFieldType::kProtoUint64},
            {"heap_name", ProtoFieldType::kProtoString},
            {"len", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "ion_cp_secure_buffer_start",
        {
            {},
            {"align", ProtoFieldType::kProtoUint64},
            {"flags", ProtoFieldType::kProtoUint64},
            {"heap_name", ProtoFieldType::kProtoString},
            {"len", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "ion_prefetching",
        {
            {},
            {"len", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "ion_secure_cma_add_to_pool_end",
        {
            {},
            {"is_prefetch", ProtoFieldType::kProtoUint32},
            {"len", ProtoFieldType::kProtoUint64},
            {"pool_total", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ion_secure_cma_add_to_pool_start",
        {
            {},
            {"is_prefetch", ProtoFieldType::kProtoUint32},
            {"len", ProtoFieldType::kProtoUint64},
            {"pool_total", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "ion_secure_cma_allocate_end",
        {
            {},
            {"align", ProtoFieldType::kProtoUint64},
            {"flags", ProtoFieldType::kProtoUint64},
            {"heap_name", ProtoFieldType::kProtoString},
            {"len", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "ion_secure_cma_allocate_start",
        {
            {},
            {"align", ProtoFieldType::kProtoUint64},
            {"flags", ProtoFieldType::kProtoUint64},
            {"heap_name", ProtoFieldType::kProtoString},
            {"len", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "ion_secure_cma_shrink_pool_end",
        {
            {},
            {"drained_size", ProtoFieldType::kProtoUint64},
            {"skipped_size", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "ion_secure_cma_shrink_pool_start",
        {
            {},
            {"drained_size", ProtoFieldType::kProtoUint64},
            {"skipped_size", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "kfree",
        {
            {},
            {"call_site", ProtoFieldType::kProtoUint64},
            {"ptr", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "kmalloc",
        {
            {},
            {"bytes_alloc", ProtoFieldType::kProtoUint64},
            {"bytes_req", ProtoFieldType::kProtoUint64},
            {"call_site", ProtoFieldType::kProtoUint64},
            {"gfp_flags", ProtoFieldType::kProtoUint32},
            {"ptr", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "kmalloc_node",
        {
            {},
            {"bytes_alloc", ProtoFieldType::kProtoUint64},
            {"bytes_req", ProtoFieldType::kProtoUint64},
            {"call_site", ProtoFieldType::kProtoUint64},
            {"gfp_flags", ProtoFieldType::kProtoUint32},
            {"node", ProtoFieldType::kProtoInt32},
            {"ptr", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "kmem_cache_alloc",
        {
            {},
            {"bytes_alloc", ProtoFieldType::kProtoUint64},
            {"bytes_req", ProtoFieldType::kProtoUint64},
            {"call_site", ProtoFieldType::kProtoUint64},
            {"gfp_flags", ProtoFieldType::kProtoUint32},
            {"ptr", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "kmem_cache_alloc_node",
        {
            {},
            {"bytes_alloc", ProtoFieldType::kProtoUint64},
            {"bytes_req", ProtoFieldType::kProtoUint64},
            {"call_site", ProtoFieldType::kProtoUint64},
            {"gfp_flags", ProtoFieldType::kProtoUint32},
            {"node", ProtoFieldType::kProtoInt32},
            {"ptr", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "kmem_cache_free",
        {
            {},
            {"call_site", ProtoFieldType::kProtoUint64},
            {"ptr", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "migrate_pages_end",
        {
            {},
            {"mode", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "migrate_pages_start",
        {
            {},
            {"mode", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "migrate_retry",
        {
            {},
            {"tries", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "mm_page_alloc",
        {
            {},
            {"gfp_flags", ProtoFieldType::kProtoUint32},
            {"migratetype", ProtoFieldType::kProtoInt32},
            {"order", ProtoFieldType::kProtoUint32},
            {"page", ProtoFieldType::kProtoUint64},
            {"pfn", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "mm_page_alloc_extfrag",
        {
            {},
            {"alloc_migratetype", ProtoFieldType::kProtoInt32},
            {"alloc_order", ProtoFieldType::kProtoInt32},
            {"fallback_migratetype", ProtoFieldType::kProtoInt32},
            {"fallback_order", ProtoFieldType::kProtoInt32},
            {"page", ProtoFieldType::kProtoUint64},
            {"change_ownership", ProtoFieldType::kProtoInt32},
            {"pfn", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "mm_page_alloc_zone_locked",
        {
            {},
            {"migratetype", ProtoFieldType::kProtoInt32},
            {"order", ProtoFieldType::kProtoUint32},
            {"page", ProtoFieldType::kProtoUint64},
            {"pfn", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "mm_page_free",
        {
            {},
            {"order", ProtoFieldType::kProtoUint32},
            {"page", ProtoFieldType::kProtoUint64},
            {"pfn", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "mm_page_free_batched",
        {
            {},
            {"cold", ProtoFieldType::kProtoInt32},
            {"page", ProtoFieldType::kProtoUint64},
            {"pfn", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "mm_page_pcpu_drain",
        {
            {},
            {"migratetype", ProtoFieldType::kProtoInt32},
            {"order", ProtoFieldType::kProtoUint32},
            {"page", ProtoFieldType::kProtoUint64},
            {"pfn", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "rss_stat",
        {
            {},
            {"member", ProtoFieldType::kProtoInt32},
            {"size", ProtoFieldType::kProtoInt64},
        },
    },
    {
        "ion_heap_shrink",
        {
            {},
            {"heap_name", ProtoFieldType::kProtoString},
            {"len", ProtoFieldType::kProtoUint64},
            {"total_allocated", ProtoFieldType::kProtoInt64},
        },
    },
    {
        "ion_heap_grow",
        {
            {},
            {"heap_name", ProtoFieldType::kProtoString},
            {"len", ProtoFieldType::kProtoUint64},
            {"total_allocated", ProtoFieldType::kProtoInt64},
        },
    },
    {
        "fence_init",
        {
            {},
            {"context", ProtoFieldType::kProtoUint32},
            {"driver", ProtoFieldType::kProtoString},
            {"seqno", ProtoFieldType::kProtoUint32},
            {"timeline", ProtoFieldType::kProtoString},
        },
    },
    {
        "fence_destroy",
        {
            {},
            {"context", ProtoFieldType::kProtoUint32},
            {"driver", ProtoFieldType::kProtoString},
            {"seqno", ProtoFieldType::kProtoUint32},
            {"timeline", ProtoFieldType::kProtoString},
        },
    },
    {
        "fence_enable_signal",
        {
            {},
            {"context", ProtoFieldType::kProtoUint32},
            {"driver", ProtoFieldType::kProtoString},
            {"seqno", ProtoFieldType::kProtoUint32},
            {"timeline", ProtoFieldType::kProtoString},
        },
    },
    {
        "fence_signaled",
        {
            {},
            {"context", ProtoFieldType::kProtoUint32},
            {"driver", ProtoFieldType::kProtoString},
            {"seqno", ProtoFieldType::kProtoUint32},
            {"timeline", ProtoFieldType::kProtoString},
        },
    },
    {
        "clk_enable",
        {
            {},
            {"name", ProtoFieldType::kProtoString},
        },
    },
    {
        "clk_disable",
        {
            {},
            {"name", ProtoFieldType::kProtoString},
        },
    },
    {
        "clk_set_rate",
        {
            {},
            {"name", ProtoFieldType::kProtoString},
            {"rate", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "binder_transaction_alloc_buf",
        {
            {},
            {"data_size", ProtoFieldType::kProtoUint64},
            {"debug_id", ProtoFieldType::kProtoInt32},
            {"offsets_size", ProtoFieldType::kProtoUint64},
        },
    },
    {
        "signal_deliver",
        {
            {},
            {"code", ProtoFieldType::kProtoInt32},
            {"sa_flags", ProtoFieldType::kProtoUint64},
            {"sig", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "signal_generate",
        {
            {},
            {"code", ProtoFieldType::kProtoInt32},
            {"comm", ProtoFieldType::kProtoString},
            {"group", ProtoFieldType::kProtoInt32},
            {"pid", ProtoFieldType::kProtoInt32},
            {"result", ProtoFieldType::kProtoInt32},
            {"sig", ProtoFieldType::kProtoInt32},
        },
    },
    {
        "oom_score_adj_update",
        {
            {},
            {"comm", ProtoFieldType::kProtoString},
            {"oom_score_adj", ProtoFieldType::kProtoInt32},
            {"pid", ProtoFieldType::kProtoInt32},
        },
    },
    {},
}};
}  // namespace perfetto
#endif  // SRC_TRACE_PROCESSOR_FTRACE_DESCRIPTORS_H_
