/*
 * Copyright (C) 2017 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*******************************************************************************
 * AUTOGENERATED - DO NOT EDIT
 *******************************************************************************
 * This file has been generated from the protobuf message
 * perfetto/config/process_tree/process_tree_config.proto
 * by
 * ../../tools/proto_to_cpp/proto_to_cpp.cc.
 * If you need to make changes here, change the .proto file and then run
 * ./tools/gen_tracing_cpp_headers_from_protos.py
 */

#include "perfetto/tracing/core/process_tree_config.h"

#include "perfetto/config/process_tree/process_tree_config.pb.h"

namespace perfetto {

ProcessTreeConfig::ProcessTreeConfig() = default;
ProcessTreeConfig::~ProcessTreeConfig() = default;
ProcessTreeConfig::ProcessTreeConfig(const ProcessTreeConfig&) = default;
ProcessTreeConfig& ProcessTreeConfig::operator=(const ProcessTreeConfig&) =
    default;
ProcessTreeConfig::ProcessTreeConfig(ProcessTreeConfig&&) noexcept = default;
ProcessTreeConfig& ProcessTreeConfig::operator=(ProcessTreeConfig&&) = default;

void ProcessTreeConfig::FromProto(
    const perfetto::protos::ProcessTreeConfig& proto) {
  flags_.clear();
  for (const auto& field : proto.flags()) {
    flags_.emplace_back();
    static_assert(sizeof(flags_.back()) == sizeof(proto.flags(0)),
                  "size mismatch");
    flags_.back() = static_cast<decltype(flags_)::value_type>(field);
  }
  unknown_fields_ = proto.unknown_fields();
}

void ProcessTreeConfig::ToProto(
    perfetto::protos::ProcessTreeConfig* proto) const {
  proto->Clear();

  for (const auto& it : flags_) {
    proto->add_flags(static_cast<decltype(proto->flags(0))>(it));
    static_assert(sizeof(it) == sizeof(proto->flags(0)), "size mismatch");
  }
  *(proto->mutable_unknown_fields()) = unknown_fields_;
}

}  // namespace perfetto
