#!/bin/bash
# Copyright (C) 2018 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

CUR_DIR="$(cd -P ${BASH_SOURCE[0]%/*}; pwd)"
BASE_PERFETTO_DIR="$(cd $CUR_DIR/..; pwd)"
RESOLVED_OUTPUT_DIR="$(cd $CUR_DIR/dist; pwd -P)"
OUTPUT_BASE_DIR="$(dirname $RESOLVED_OUTPUT_DIR)"
NINJA_OUT_DIR="$(python -c\
 "import os.path;\
 print os.path.relpath('$OUTPUT_BASE_DIR', '$BASE_PERFETTO_DIR')" \
)"

LITE_SERVER="$CUR_DIR/node_modules/.bin/lite-server"
if [ ! -f "$LITE_SERVER" ]; then
  echo "ERROR: cannot find lite-server. You need to run:"
  echo "  tools/install-build-deps --ui"
  echo "  ninja -C out/xxx ui"
  exit 127
fi
if [ ! -L "$CUR_DIR/dist" ]; then
  echo "ERROR: cannot find the 'dist' symlink. Did you run ninja?"
  exit 127
fi

export PATH="$CUR_DIR/../buildtools/nodejs/bin/:$PATH"
cd "$CUR_DIR/../"
NINJA_OUT_DIR="$NINJA_OUT_DIR" \
    node ui/node_modules/.bin/lite-server -c ui/bs-config.js
